/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto.csv.view;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import projeto.csv.model.Csv;

/**
 *
 * @author Junior
 */
public class TelaLocalizarArquivoView extends javax.swing.JFrame {

    /**
     * Creates new form TelaLocalizarArquivoView
     */
   
    public TelaLocalizarArquivoView() {
        initComponents();
        SetIcon();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbArquivo = new javax.swing.JButton();
        texSelecionarArquivo = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbArquivo.setText("Procurar");
        jbArquivo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(jbArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 90, 30));

        texSelecionarArquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                texSelecionarArquivoActionPerformed(evt);
            }
        });
        getContentPane().add(texSelecionarArquivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 30));

        btnVerificar.setText("Verificar diretório");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 360, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projeto/csv/imagens/0_kwz8d_aG00d3fPln.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbArquivoActionPerformed
        try {
           JFileChooser fc = new JFileChooser();
           fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
           fc.showOpenDialog(this);
           File f = fc.getSelectedFile();
           
           texSelecionarArquivo.setText(f.getPath());
        } catch (Exception e) {
            
        }
  
      
           
           
           
    }//GEN-LAST:event_jbArquivoActionPerformed

    private void texSelecionarArquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_texSelecionarArquivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_texSelecionarArquivoActionPerformed

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
     
        String caminho = texSelecionarArquivo.getText();
        if(!caminho.equals("")){
            File folder = new File(caminho);
            Csv modelCsv = new Csv(folder);
            try {
                modelCsv.ler_arquivos_diretorio();
            } catch (IOException ex) {
                
            }
           JOptionPane.showMessageDialog(rootPane, "Quantidade de CSV validados:"+modelCsv.getContadorValido()+"\n Quantidade de CSV Invalidados:"+modelCsv.getContadorInvalido());

           
           
        }else{
            JOptionPane.showMessageDialog(rootPane, "Selecione um diretório");
        }
        
    }//GEN-LAST:event_btnVerificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizarArquivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizarArquivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizarArquivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLocalizarArquivoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbArquivo;
    private javax.swing.JTextField texSelecionarArquivo;
    // End of variables declaration//GEN-END:variables

    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("csv.png")));
    }
}
